id: AC9C619EA
title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
type: translation
pechas:
- I780747D2
- I7807221C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:28.798160
  last_modified_at: 2023-01-04 11:36:28.798179
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I780747D2/E5EB: 5C2D
  I7807221C/4344: 5C2D
